version: "3"
services:
  api:
    build: .
    image: spa_svelte_js_hello-world:basic-authn-with-api
    container_name: spa_svelte_js_hello-world_basic-authn-with-api
    ports:
      - 4040:4040
    env_file:
      - .env
